[package]
name = "unitconvert"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
strum = "0.27.1"
strum_macros = "0.27.1"
thiserror = "2"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
